// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_an_apple_a_day = "CgkI9rTrn4oQEAIQDA"; // <GPGSID>
        public const string achievement_water_meloooooonnnnnnnnn = "CgkI9rTrn4oQEAIQEQ"; // <GPGSID>
        public const string achievement_can_i_have_loan = "CgkI9rTrn4oQEAIQCg"; // <GPGSID>
        public const string achievement_a_100_big_ones = "CgkI9rTrn4oQEAIQBg"; // <GPGSID>
        public const string achievement_peachy = "CgkI9rTrn4oQEAIQEw"; // <GPGSID>
        public const string achievement_very_berry = "CgkI9rTrn4oQEAIQDg"; // <GPGSID>
        public const string achievement_a_cherry_on_top = "CgkI9rTrn4oQEAIQDQ"; // <GPGSID>
        public const string achievement_now_were_talking_money = "CgkI9rTrn4oQEAIQCA"; // <GPGSID>
        public const string achievement_when_life_gives_you_lemons = "CgkI9rTrn4oQEAIQFA"; // <GPGSID>
        public const string achievement_might_as_well_retire = "CgkI9rTrn4oQEAIQCw"; // <GPGSID>
        public const string achievement_a_small_loan = "CgkI9rTrn4oQEAIQBw"; // <GPGSID>
        public const string achievement_a_pair_of_pears = "CgkI9rTrn4oQEAIQEg"; // <GPGSID>
        public const string achievement_aint_it_grand = "CgkI9rTrn4oQEAIQBA"; // <GPGSID>
        public const string achievement_youre_insane = "CgkI9rTrn4oQEAIQCQ"; // <GPGSID>
        public const string achievement_i_smell_money = "CgkI9rTrn4oQEAIQAQ"; // <GPGSID>
        public const string achievement_stacking_up = "CgkI9rTrn4oQEAIQBQ"; // <GPGSID>
        public const string achievement_holy_guacamole = "CgkI9rTrn4oQEAIQDw"; // <GPGSID>
        public const string achievement_dont_slip = "CgkI9rTrn4oQEAIQEA"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkI9rTrn4oQEAIQAg"; // <GPGSID>
        public const string achievement_100_smackeroos = "CgkI9rTrn4oQEAIQAw"; // <GPGSID>

}

